### ISSUE TITLE
AttachElectronSF() crashing for 2016 APV samples 

### ISSUE THREAD

**Issue by kmohrman** [TopEFT/topcoffea#64]
When processing a UL16APV sample on the [EventSelection](https://github.com/TopEFT/topcoffea/tree/EventSelection) branch, the code crashes [here](https://github.com/TopEFT/topcoffea/blob/EventSelection/topcoffea/modules/corrections.py#L137) in `AttachElectronSF()` with the key error pasted below. An example cfg file that should produce the crash is [this](https://gist.github.com/kmohrman/0defd8a030279c9afac11edd77be3ab8). Here is the traceback:

```
Traceback (most recent call last):
  File "/afs/crc.nd.edu/user/k/kmohrman/miniconda3/envs/coffea-env-current/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/afs/crc.nd.edu/user/k/kmohrman/miniconda3/envs/coffea-env-current/lib/python3.8/site-packages/coffea/processor/executor.py", line 186, in __call__
    out = self.function(*args, **kwargs)
  File "/afs/crc.nd.edu/user/k/kmohrman/miniconda3/envs/coffea-env-current/lib/python3.8/site-packages/coffea/processor/executor.py", line 1167, in _work_function
    raise e
  File "/afs/crc.nd.edu/user/k/kmohrman/miniconda3/envs/coffea-env-current/lib/python3.8/site-packages/coffea/processor/executor.py", line 1120, in _work_function
    raise type(e)(str(e) + file_trace).with_traceback(
  File "/afs/crc.nd.edu/user/k/kmohrman/miniconda3/envs/coffea-env-current/lib/python3.8/site-packages/coffea/processor/executor.py", line 1117, in _work_function
    out = processor_instance.process(events)
  File "/afs/crc.nd.edu/user/k/kmohrman/coffea_dir/topcoffea_EventSelection/topcoffea/analysis/topEFT/topeft.py", line 111, in process
    AttachElectronSF(e_fo,year=year)
  File "/afs/crc.nd.edu/user/k/kmohrman/coffea_dir/topcoffea_EventSelection/topcoffea/topcoffea/modules/corrections.py", line 137, in AttachElectronSF
    reco_sf          = SFevaluator['ElecRecoSF_{year}'.format(year=year)](eta,pt)
  File "/afs/crc.nd.edu/user/k/kmohrman/miniconda3/envs/coffea-env-current/lib/python3.8/site-packages/coffea/lookup_tools/evaluator.py", line 58, in __getitem__
    return self._functions[key]
KeyError: "'ElecRecoSF_2016APV'\n\nFailed processing file: root://deepthought.crc.nd.edu//store/user/kmohrman/FullProduction/FullR2/UL16APV/Round1/Batch1/naodOnly_step/v1/nAOD_step_tHq4f_all22WCsStartPtCheckdim6TopMay20GST_run0/NAOD-00000_8595.root (0-10)"
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run.py", line 159, in <module>
    output = processor.run_uproot_job(flist, treename=treename, processor_instance=processor_instance, executor=processor.futures_executor, executor_args={"schema": NanoAODSchema,'workers': nworkers, 'pre_workers': 1}, chunksize=chunksize, maxchunks=nchunks)
  File "/afs/crc.nd.edu/user/k/kmohrman/miniconda3/envs/coffea-env-current/lib/python3.8/site-packages/coffea/processor/executor.py", line 1466, in run_uproot_job
    wrapped_out = executor(chunks, closure, None, **exe_args)
  File "/afs/crc.nd.edu/user/k/kmohrman/miniconda3/envs/coffea-env-current/lib/python3.8/site-packages/coffea/processor/executor.py", line 791, in futures_executor
    return processwith(poolinstance)
  File "/afs/crc.nd.edu/user/k/kmohrman/miniconda3/envs/coffea-env-current/lib/python3.8/site-packages/coffea/processor/executor.py", line 773, in processwith
    return accumulate(
  File "/afs/crc.nd.edu/user/k/kmohrman/miniconda3/envs/coffea-env-current/lib/python3.8/site-packages/coffea/processor/accumulator.py", line 89, in accumulate
    accum = next(gen)
  File "/afs/crc.nd.edu/user/k/kmohrman/miniconda3/envs/coffea-env-current/lib/python3.8/site-packages/coffea/processor/accumulator.py", line 86, in <genexpr>
    gen = (x for x in items if x is not None)
  File "/afs/crc.nd.edu/user/k/kmohrman/miniconda3/envs/coffea-env-current/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/afs/crc.nd.edu/user/k/kmohrman/miniconda3/envs/coffea-env-current/lib/python3.8/site-packages/coffea/processor/executor.py", line 237, in _futures_handler
    yield done.pop().result()
  File "/afs/crc.nd.edu/user/k/kmohrman/miniconda3/envs/coffea-env-current/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/afs/crc.nd.edu/user/k/kmohrman/miniconda3/envs/coffea-env-current/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
KeyError: "'ElecRecoSF_2016APV'\n\nFailed processing file: root://deepthought.crc.nd.edu//store/user/kmohrman/FullProduction/FullR2/UL16APV/Round1/Batch1/naodOnly_step/v1/nAOD_step_tHq4f_all22WCsStartPtCheckdim6TopMay20GST_run0/NAOD-00000_8595.root (0-10)"
```

**Comment by klannon** [comment]
Are there separate electron SF's for the 2016 and 2016APV, or should they both use 2016?

**Comment by kmohrman** [comment]
Thanks, @klannon! I was looking at [this page](https://gitlab.cern.ch/ttH_leptons/doc/-/blob/master/Legacy/data_to_mc_corrections.md) linked from the [readme](https://github.com/TopEFT/topcoffea/tree/master/topcoffea/data/fromTTH/lepSF#readme) in our `topcoffea/data/fromTTH/lepSF` directory, and I don't seem to see anything about APV, so maybe this implies that there are not separate SFs for 2016 and 2016 APV. But I am certainly not an expert, so maybe @andrea21z could comment on this?
